/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/police.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/police.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wheel-back-left'].geometry} material={materials.colormap} position={[0.3, 0.3, -0.81]} />
      <mesh geometry={nodes['wheel-front-left'].geometry} material={materials.colormap} position={[0.3, 0.3, 0.81]} />
      <mesh geometry={nodes['wheel-back-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, -0.81]} />
      <mesh geometry={nodes.body.geometry} material={materials.colormap} position={[0, 0.2, -0.025]}>
        <mesh geometry={nodes.grill.geometry} material={materials.colormap} position={[0, 0.074, 1.475]} />
      </mesh>
      <mesh geometry={nodes['wheel-front-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, 0.81]} />
    </group>
  )
}

useGLTF.preload('/police.glb')
