/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 D:\Wreck Race\kenney_car-kit\Models\GLB format\sedan.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/sedan.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['wheel-front-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, 0.66]} />
      <mesh geometry={nodes.body.geometry} material={materials.colormap} position={[0, 0.15, -0.025]} />
      <mesh geometry={nodes['wheel-back-left'].geometry} material={materials.colormap} position={[0.3, 0.3, -0.66]} />
      <mesh geometry={nodes['wheel-back-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, -0.66]} />
      <mesh geometry={nodes['wheel-front-left'].geometry} material={materials.colormap} position={[0.3, 0.3, 0.66]} />
    </group>
  )
}

useGLTF.preload('/sedan.glb')
