/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/suv.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/suv.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={materials.colormap} position={[0, 0.2, 0]}>
        <mesh geometry={nodes['wheel-back'].geometry} material={materials.colormap} position={[0, 0.5, -1.05]} />
      </mesh>
      <mesh geometry={nodes['wheel-back-left'].geometry} material={materials.colormap} position={[0.3, 0.3, -0.56]} />
      <mesh geometry={nodes['wheel-back-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, -0.56]} />
      <mesh geometry={nodes['wheel-front-left'].geometry} material={materials.colormap} position={[0.3, 0.3, 0.76]} />
      <mesh geometry={nodes['wheel-front-right'].geometry} material={materials.colormap} position={[-0.3, 0.3, 0.76]} />
    </group>
  )
}

useGLTF.preload('/suv.glb')
